name: Default
on:
  - push
jobs:
  check-gradle-version:
    name: Check Gradle version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: madhead/check-gradle-version@v1
    continue-on-error: true
  check:
    name: Default
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
      - run: ./gradlew clean check
